fix: run.sh provides a value to --allow-parse-errors (#712)
I noticed that `helpers/inspect.sh` kept failing and generating blank output, and it is because the `--allow-parse-errors` must have a value:

```
$ helpers/inspect.sh examples/emacs-lisp/working/two-toplevel/
error: a value is required for '--allow-parse-errors <ALLOW_PARSE_ERRORS>' but none was supplied
  [possible values: true, false]

For more information, try '--help'.
------ RESULT ------
------ BASE --------
(initial-form)
------ LEFT --------
(initial-form)
(left-form)
------ RIGHT --------
(initial-form)
(right-form)
------ EXPECTED --------
(initial-form)
(left-form)
(right-form)
------ diff ------
*** /tmp/expected5595.el	Fri Feb 13 23:53:28 2026
--- /tmp/out5595.el	Fri Feb 13 23:53:28 2026
***************
*** 1,3 ****
- (initial-form)
- (left-form)
- (right-form)
--- 0 ----
```

So, this includes allowing parse errors by default for the inspector scripts.

Co-authored-by: Chris Rose <offline@offby1.net>
Reviewed-on: https://codeberg.org/mergiraf/mergiraf/pulls/712
Reviewed-by: Antonin Delpeuch <wetneb@noreply.codeberg.org>
Co-authored-by: offby1 <offby1@noreply.codeberg.org>
Co-committed-by: offby1 <offby1@noreply.codeberg.org>